apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cHJvZ3Jlc3NkYg==

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: db-config
# data:
#   db-url: "postgresql://postgres:postgres@db:5432/progressdb?sslmode=disable"
