version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: progressdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/progressdb?sslmode=disable"
